name: Test
on:
  push:
    branches-ignore: [debian]

jobs:
  test:
    name: ${{ matrix.redmine }} on ${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - ruby: "2.7"
            redmine: "4.2.1"
          - ruby: "2.6"
            redmine: "4.1.3"
      fail-fast: false

    env:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
      BUNDLE_RETRY: 3
      BUNDLE_WITHOUT: development
      REDMINE_VERSION: ${{ matrix.redmine }}

    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: setup cache
        uses: actions/cache@v1
        with:
          path: vendor
          # Updating v<x> to v<x+1> clear the cache
          key: v4-ruby-${{ matrix.ruby }}-redmine-${{ matrix.redmine }}

      - name: install ruby dependencies
        run: bundle install

      - name: setup redmine ${{ matrix.redmine }}
        run: ./redmine update

      - name: run prepare tests
        run: ./redmine exec bundle exec rake db:test:prepare

      - name: run plugins tests
        run: ./redmine exec bundle exec rake redmine:plugins:test
